config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }, skip: [:sessions]

  as :user do
    get 'participar' => "devise/sessions#new", as: :new_user_session
    post 'signin' => 'devise/sessions#create', as: :user_session
    delete 'sair' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  match '/perfil' => 'users#account', via: [:get, :patch], as: :account

  namespace :zone do
    root 'dashboard#index'
    get '/stats(/:state/:position)' => 'dashboard#stats', as: :stats
    post '/search' => "candidates#index"
    resources :elections, only: [:index, :create]
    resources :users, only: [:index, :edit, :update]
    resources :candidates
    resources :issues, only: [:index, :update, :edit, :show]
  end

  resources :issues, only: [:create]

  get '/simulador', to: 'votes#index', as: :simulator
  get '/simulador/resultados', to: 'votes#results', as: :results
  get '/simulador/resultados/imprimir', to: 'votes#print', as: :print
  post '/vote', to: 'votes#create', as: :vote
  get '/:position/:number', to: 'candidates#show', as: :candidates
  get '/estatisticas(/:state/:position)', to: 'stats#charts', as: :charts
  get '/politica-de-privacidade', to: 'elections#politics', as: :politics
  get '/reportar-erro', to: 'issues#new', as: :issue

  root 'elections#index'

end

app/models/issue.rb
class Issue < ActiveRecord::Base

  STATUSES = {
    'Novo' => 'Novo',
    'Em andamento' => 'Em andamento',
    'Ignorado' => 'Ignorado',
    'Resolvido' => 'Resolvido'
  }

  belongs_to :user
  validates :message, presence: true

  before_create :init

  def init
    self.status = 'Novo'
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  def new
    @issue = Issue.new
  end

  def create
    @issue = Issue.new issue_params
    @issue.user = current_user if current_user
    @issue.save
    redirect_to :back, notice: 'Valeu! Recebemos seu recado!'
  end

  private

    def issue_params
      params.require(:issue).permit(:message)
    end
end

app/controllers/zone/candidates_controller.rb
class Zone::CandidatesController < InheritedResources::Base
  include CandidatesHelper
  before_action :authenticate_admin!
  layout 'admin'

  def index
    @candidates = params[:term] ? Candidate.search(params[:term]).results : Candidate.active.where(election: current_election).page(params[:page])
    render action: :index
  end

  private

    def candidate_params
      params.require(:candidate).permit(:name, :ballot_name, :position, :number, :entourage, :status, :union, :state, :election_id)
    end
end

app/controllers/zone/dashboard_controller.rb
class Zone::DashboardController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'

  def index
    @votes = Vote.where(election_id: current_election.id).size
    @users = User.all.size
    @candidates = Candidate.active.where(election_id: current_election.id).size
    @issues = Issue.all.size
  end

  def stats
    @candidates =
      Candidate.active.where(election_id: current_election.id,
        position: (params[:position].try(:capitalize)||'Presidente'),
        state: (params[:state].try(:upcase)||'BR')).order(:id)
    @data = @candidates.select(:ballot_name, :votes_counter).to_json
  end

end

app/controllers/zone/elections_controller.rb
class Zone::ElectionsController < InheritedResources::Base
  before_action :authenticate_admin!
  layout 'admin'

  def index
    @election = Election.new
    super
  end

  def create
    super do |format|
      format.html { redirect_to zone_elections_url }
    end
  end

  private

    def election_params
      params.require(:election).permit(:year, :round)
    end

end

app/controllers/zone/issues_controller.rb
class Zone::IssuesController < InheritedResources::Base
  before_action :authenticate_admin!
  layout 'admin'
  actions :index, :show, :edit, :update

  private

    def issue_params
      params.require(:issue).permit(:status)
    end

end

app/controllers/zone/users_controller.rb
class Zone::UsersController < InheritedResources::Base
  before_action :authenticate_admin!
  layout 'admin'
  actions :index, :edit, :update

  def index
    @users = User.all.order(id: :desc).page params[:page]
  end

  protected

    def user_params
      params.require(:user).permit(:email, :name, :state)
    end
end

app/helpers/zone/issues_helper.rb
module Zone::IssuesHelper

  STATUSES = {
    'novo' => 'success',
    'em andamento' => 'warning',
    'ignorado' => 'mute',
    'resolvido' => 'none'
  }

  def class_for status
    return STATUSES[status.downcase]
  end

end

app/views/zone/issues/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Mensagem enviada pelo site</h1>
  </div>
</div>

<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">Editar</div>

    <div class="panel-body">

      <%= form_for([:zone, @issue], html: { role: 'form', class: 'form-horizontal' }) do |f| %>
        <% if @issue.user %>De: <%= @issue.user.name %> (<%= @issue.user.email %>)<br><br><% end %>
        <%= f.text_area :message, autofocus: true, class: 'form-control', disabled: true, rows: 20 %><br>
        <%= f.select :status, Issue::STATUSES.map{|status|[status[0], status[0]]}, { include_blank: false }, { class: 'form-control input-lg' } %><br><br>
        <%= f.submit "Enviar", class: 'btn btn-lg btn-primary btn-block' %>
      <% end %>

    </div>
  </div>
</div>

app/views/zone/issues/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Mensagens</h1>
  </div>
</div>

<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">Lista</div>

    <div class="panel-body">

      <div class="table-responsive">

        <table class="table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Data/Hora</th>
              <th>Status</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @issues.order(created_at: :desc).each do |issue| %>
              <tr class="<%= class_for issue.status %>">
                <td><%= issue.id %></td>
                <td><%= issue.created_at.strftime("%d/%m/%Y %H:%M") %></td>
                <td><%= issue.status %></td>
                <td>
                  <%= link_to 'ver', zone_issue_path(issue) %> | <%= link_to 'editar', edit_zone_issue_path(issue) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

app/views/zone/issues/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Mensagem recebida em <%= @issue.created_at.strftime("%d/%m/%Y %H:%M") %></h1>
  </div>
</div>

<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">Dados</div>

    <div class="panel-body">
      <% if @issue.user %>De: <%= @issue.user.name %> (<%= @issue.user.email %>)<br><% end %>
      <p>Situação: <%= @issue.status %></p>

      <p><%= simple_format @issue.message %></p>
    </div>

  </div>

  <%= link_to '< Voltar', zone_issues_path, class: 'btn btn-primary' %>
  <%= link_to 'Editar', edit_zone_issue_path(@issue), class: 'btn btn-primary' %>

</div>