config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }, skip: [:sessions]

  as :user do
    get 'participar' => "devise/sessions#new", as: :new_user_session
    post 'signin' => 'devise/sessions#create', as: :user_session
    delete 'sair' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  match '/perfil' => 'users#account', via: [:get, :patch], as: :account

  namespace :zone do
    root 'dashboard#index'
    get '/stats(/:state/:position)' => 'dashboard#stats', as: :stats
    post '/search' => "candidates#index"
    resources :elections, only: [:index, :create]
    resources :users, only: [:index, :edit, :update]
    resources :candidates
    resources :issues, only: [:index, :update, :edit, :show]
  end

  resources :issues, only: [:create]

  get '/simulador', to: 'votes#index', as: :simulator
  get '/simulador/resultados', to: 'votes#results', as: :results
  get '/simulador/resultados/imprimir', to: 'votes#print', as: :print
  post '/vote', to: 'votes#create', as: :vote
  get '/:position/:number', to: 'candidates#show', as: :candidates
  get '/estatisticas(/:state/:position)', to: 'stats#charts', as: :charts
  get '/politica-de-privacidade', to: 'elections#politics', as: :politics
  get '/reportar-erro', to: 'issues#new', as: :issue

  root 'elections#index'

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  include StatsHelper
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  validates :name, :ballot_name, :position, :number, :entourage, :status, :union, :election, presence: true
  validates :number, uniqueness: { scope: [:position, :state, :election_id] }

  has_many :votes
  has_many :stats
  belongs_to :election

  scope :active, -> { where(status: 'Deferido') }

  def self.decrement_vote id
    candidate = self.find id
    candidate.votes_counter ||= 0
    candidate.update_column :votes_counter, candidate.votes_counter-1 if candidate
  end

  def votes_to_percent
    # totals = TotalStat.where(election: self.election, position: self.position, state: self.state).first
    total = Candidate.active.where(election_id: self.election_id, position: self.position, state: self.state).sum(:votes_counter)
    self.votes_counter = 0 if self.votes_counter.nil?
    percent = (total > 0) ? (self.votes_counter * 100)/total : 0
    return percent
  end

  def votes_for_days count = 5
    days = last_days(count)
    stats = self.stats.betweens_dates(days.first, days.last)
    votes = Array.new(count - stats.size, 0)

    stats.order(:created_at).each do |stats|
      votes.push(stats.votes || 0)
    end

    return votes
  end

end

app/controllers/candidates_controller.rb
class CandidatesController < InheritedResources::Base
  include CandidatesHelper

  before_action :authenticate_user!
  actions :show

  def show
    # TODO: elasticsearch aqui
    position = CandidatesHelper::POSITIONS[params[:position]]

    unless params[:position] == 'presidente'
      position = 'Deputado Distrital' if current_user.state == 'DF'
      @candidate = Candidate.active.where(position: position,
              election: current_election,
              number: params[:number],
              state: current_user.state).first
    else
      @candidate = Candidate.active.where(position: position,
              election: current_election,
              number: params[:number],
              state: 'BR').first
    end

    render json: (@candidate || { ballot_name: 'Vote Nulo', entourage: 'Vote Nulo' })
  end

end

app/controllers/zone/candidates_controller.rb
class Zone::CandidatesController < InheritedResources::Base
  include CandidatesHelper
  before_action :authenticate_admin!
  layout 'admin'

  def index
    @candidates = params[:term] ? Candidate.search(params[:term]).results : Candidate.active.where(election: current_election).page(params[:page])
    render action: :index
  end

  private

    def candidate_params
      params.require(:candidate).permit(:name, :ballot_name, :position, :number, :entourage, :status, :union, :state, :election_id)
    end
end

app/controllers/zone/dashboard_controller.rb
class Zone::DashboardController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'

  def index
    @votes = Vote.where(election_id: current_election.id).size
    @users = User.all.size
    @candidates = Candidate.active.where(election_id: current_election.id).size
    @issues = Issue.all.size
  end

  def stats
    @candidates =
      Candidate.active.where(election_id: current_election.id,
        position: (params[:position].try(:capitalize)||'Presidente'),
        state: (params[:state].try(:upcase)||'BR')).order(:id)
    @data = @candidates.select(:ballot_name, :votes_counter).to_json
  end

end

app/controllers/zone/elections_controller.rb
class Zone::ElectionsController < InheritedResources::Base
  before_action :authenticate_admin!
  layout 'admin'

  def index
    @election = Election.new
    super
  end

  def create
    super do |format|
      format.html { redirect_to zone_elections_url }
    end
  end

  private

    def election_params
      params.require(:election).permit(:year, :round)
    end

end

app/controllers/zone/issues_controller.rb
class Zone::IssuesController < InheritedResources::Base
  before_action :authenticate_admin!
  layout 'admin'
  actions :index, :show, :edit, :update

  private

    def issue_params
      params.require(:issue).permit(:status)
    end

end

app/controllers/zone/users_controller.rb
class Zone::UsersController < InheritedResources::Base
  before_action :authenticate_admin!
  layout 'admin'
  actions :index, :edit, :update

  def index
    @users = User.all.order(id: :desc).page params[:page]
  end

  protected

    def user_params
      params.require(:user).permit(:email, :name, :state)
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper

  POSITIONS = {
    'deputado-estadual' => 'Deputado Estadual',
    'deputado-federal' => 'Deputado Federal',
    'governador' => 'Governador',
    'senador' => 'Senador',
    'presidente' => 'Presidente'
   }

  STATES = {
    'AC' => 'Acre',
    'AL' => 'Alagoas',
    'AM' => 'Amazonas',
    'AP' => 'Amapá',
    'BA' => 'Bahia',
    'CE' => 'Ceará',
    'DF' => 'Distrito Federal',
    'ES' => 'Espírito Santo',
    'GO' => 'Goiás',
    'MA' => 'Maranhão',
    'MG' => 'Minas Gerais',
    'MS' => 'Mato Grosso do Sul',
    'MT' => 'Mato Grosso',
    'PA' => 'Pará',
    'PB' => 'Paraíba',
    'PE' => 'Pernambuco',
    'PI' => 'Piauí',
    'PR' => 'Paraná',
    'RJ' => 'Rio de Janeiro',
    'RN' => 'Rio Grande do Norte',
    'RR' => 'Roraima',
    'RO' => 'Rondônia',
    'RS' => 'Rio Grande do Sul',
    'SC' => 'Santa Catarina',
    'SE' => 'Sergipe',
    'SP' => 'São Paulo',
    'TO' => 'Tocantins'
  }

  STATES_2ROUND = {
    'AC' => 'Acre',
    'AM' => 'Amazonas',
    'AP' => 'Amapá',
    'CE' => 'Ceará',
    'DF' => 'Distrito Federal',
    'GO' => 'Goiás',
    'MS' => 'Mato Grosso do Sul',
    'PA' => 'Pará',
    'PB' => 'Paraíba',
    'RJ' => 'Rio de Janeiro',
    'RN' => 'Rio Grande do Norte',
    'RR' => 'Roraima',
    'RO' => 'Rondônia',
    'RS' => 'Rio Grande do Sul'
  }

end

app/helpers/zone/issues_helper.rb
module Zone::IssuesHelper

  STATUSES = {
    'novo' => 'success',
    'em andamento' => 'warning',
    'ignorado' => 'mute',
    'resolvido' => 'none'
  }

  def class_for status
    return STATUSES[status.downcase]
  end

end

app/views/zone/candidates/_form.html.erb
<%= form_for([:zone, @candidate], html: { role: 'form', class: 'form-horizontal' }) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true, class: 'form-control' %><br>

  <%= f.label :ballot_name, 'Nome na Urna' %>
  <%= f.text_field :ballot_name, class: 'form-control' %><br>

  <%= f.label :number %>
  <%= f.text_field :number, class: 'form-control' %><br>

  <%= f.label :position, 'Cargo' %>
  <%= f.text_field :position, class: 'form-control' %><br>

  <%= f.label :entourage, 'Partido' %>
  <%= f.text_field :entourage, class: 'form-control' %><br>

  <%= f.label :union, 'Coligação' %>
  <%= f.text_field :union, class: 'form-control' %><br>

  <%= f.label :status %>
  <%= f.text_field :status, class: 'form-control' %><br>

  <%= f.label :state %>
  <%= f.select :state, CandidatesHelper::STATES.merge({ 'BR' => 'Brasil' }).map{|state|[state[0], state[0]]}, {}, { class: 'form-control' } %><br>

  <%= f.label :election %>
  <%= f.select :election_id, Election.all.map{|e|[e.name, e.id]}, {}, { class: 'form-control' } %><br>

  <%= f.submit "Salvar", class: 'btn btn-lg btn-primary btn-block' %>
<% end %>

app/views/zone/candidates/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Editar <%= @candidate.ballot_name %></h1>
  </div>
</div>

<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">Editar</div>

    <div class="panel-body">

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/zone/candidates/index.html.erb
<br>

  <div class="panel panel-default">
    <div class="panel-heading">
      Candidatos <%= current_election.name %>
      <%= link_to '+ adicionar', new_zone_candidate_path, class: 'pull-right' %>
    </div>

    <div class="panel-body">
      <div class="row">
        <div class="col-md-12">
          <div id="dataTables-example_filter" class="dataTables_filter pull-right">
            <%= form_tag([:zone, :search], html: { role: 'form', class: 'form-horizontal' }) do %>
              <label>Busca
                <%= search_field_tag :term, nil, class: 'form-control input-sm', 'aria-controls' => "dataTables-example" %>
              <% end %>
            </div>
        </div>
      </div>
      <div class="table-responsive">

        <table class="table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Nome na Urna</th>
              <th>Cargo</th>
              <th>Número</th>
              <th>Partido</th>
              <th>Estado</th>
              <th>Votos</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @candidates.each do |candidate| %>
              <tr>
                <td><%= candidate.id %></td>
                <td><%= candidate.ballot_name %></td>
                <td><%= candidate.position %></td>
                <td><%= candidate.number %></td>
                <td><%= candidate.entourage %></td>
                <td><%= candidate.state %></td>
                <td><%= candidate.votes_counter %></td>
                <td>
                  <%= link_to 'ver', zone_candidate_path(candidate.id) %> | <%= link_to 'editar', edit_zone_candidate_path(candidate.id) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

      </div>

      <% unless params[:term] %><%= paginate @candidates %><% end %>
    </div>
  </div>

app/views/zone/candidates/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Novo Candidato</h1>
  </div>
</div>

<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">Cadastrar</div>

    <div class="panel-body">

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/zone/candidates/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= @candidate.ballot_name %></h1>
  </div>
</div>

<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">Dados</div>

    <div class="panel-body">
      <div class="table-responsive">

        <table class="table">
          <tbody>
            <tr>
              <td>Nome</td>
              <td><%= @candidate.name %></td>
            </tr>
            <tr>
              <td>Nome na Urna</td>
              <td><%= @candidate.ballot_name %></td>
            </tr>
            <tr>
              <td>Número</td>
              <td><%= @candidate.number %></td>
            </tr>
            <tr>
              <td>Cargo</td>
              <td><%= @candidate.position %></td>
            </tr>
            <tr>
              <td>Partido</td>
              <td><%= @candidate.entourage %></td>
            </tr>
            <tr>
              <td>Estado</td>
              <td><%= @candidate.state %></td>
            </tr>
            <tr>
              <td>Coligação</td>
              <td><%= @candidate.union %></td>
            </tr>
            <tr>
              <td>Eleição</td>
              <td><%= @candidate.election.name %></td>
            </tr>
            <tr>
              <td>Situação</td>
              <td><%= @candidate.status %></td>
            </tr>
            <tr>
              <td>Votos</td>
              <td><%= @candidate.votes_counter %></td>
            </tr>

          </tbody>
        </table>

      </div>
    </div>
  </div>

  <%= link_to '< Voltar', zone_candidates_path, class: 'btn btn-primary' %>
  <%= link_to 'Editar', edit_zone_candidate_path(@candidate), class: 'btn btn-primary' %>

</div>