config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }, skip: [:sessions]

  as :user do
    get 'participar' => "devise/sessions#new", as: :new_user_session
    post 'signin' => 'devise/sessions#create', as: :user_session
    delete 'sair' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  match '/perfil' => 'users#account', via: [:get, :patch], as: :account

  namespace :zone do
    root 'dashboard#index'
    get '/stats(/:state/:position)' => 'dashboard#stats', as: :stats
    post '/search' => "candidates#index"
    resources :elections, only: [:index, :create]
    resources :users, only: [:index, :edit, :update]
    resources :candidates
    resources :issues, only: [:index, :update, :edit, :show]
  end

  resources :issues, only: [:create]

  get '/simulador', to: 'votes#index', as: :simulator
  get '/simulador/resultados', to: 'votes#results', as: :results
  get '/simulador/resultados/imprimir', to: 'votes#print', as: :print
  post '/vote', to: 'votes#create', as: :vote
  get '/:position/:number', to: 'candidates#show', as: :candidates
  get '/estatisticas(/:state/:position)', to: 'stats#charts', as: :charts
  get '/politica-de-privacidade', to: 'elections#politics', as: :politics
  get '/reportar-erro', to: 'issues#new', as: :issue

  root 'elections#index'

end

app/views/commons/_flash.html.erb
<% flash.each do |name, msg| -%>
  <div class="alert alert-<%= name %> alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= msg %>
  </div>
<% end -%>

app/views/commons/_head.html.erb
<meta charset="utf-8">
<meta name="copyright" content="A Urna">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="google-site-verification" content="WpVoVDPMauDeRLCTg_ytz2Pn2G2iNl3Ar0GY9BsFWUA" />
<%= yield :metatags %>
<meta property="og:locale" content="pt_BR">
<meta property="og:site_name" content="A Urna">
<meta property="og:type" content="website">
<meta property="fb:app_id" content="294932487369019">

<title><%= yield(:title) %></title>

<%= stylesheet_link_tag    'application', media: 'all' %>
<%= yield :stylesheets %>

<link rel="canonical" href="<%= request.path %>">
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<link rel="icon" href="/favicon.ico" type="image/x-icon">

<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->

<%= csrf_meta_tags %>

<script type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-2347706-25', 'auto');
  ga('require', 'linkid', 'linkid.js');
  ga('send', 'pageview');
</script>

app/views/commons/_menu.html.erb
<div class="container">
  <div class="row-fluid">
    <ul class="nav nav-pills pull-right">
      <li><%= link_to 'Início', root_path %></li>
      <li><%= link_to 'Estatísticas', charts_path %></li>
      <li><%= link_to 'Simulador', simulator_path %></li>
      <% if current_user %>
        <li><%= link_to 'Minha Conta', account_path %></li>
        <li><%= link_to 'Sair', destroy_user_session_path, method: 'DELETE' %></li>
        <li><%= link_to current_user.state, '', class: 'btn btn-default btn-md' %></li>
      <% end %>
    </ul>
  </div>
</div>