config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }, skip: [:sessions]

  as :user do
    get 'participar' => "devise/sessions#new", as: :new_user_session
    post 'signin' => 'devise/sessions#create', as: :user_session
    delete 'sair' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  match '/perfil' => 'users#account', via: [:get, :patch], as: :account

  namespace :zone do
    root 'dashboard#index'
    get '/stats(/:state/:position)' => 'dashboard#stats', as: :stats
    post '/search' => "candidates#index"
    resources :elections, only: [:index, :create]
    resources :users, only: [:index, :edit, :update]
    resources :candidates
    resources :issues, only: [:index, :update, :edit, :show]
  end

  resources :issues, only: [:create]

  get '/simulador', to: 'votes#index', as: :simulator
  get '/simulador/resultados', to: 'votes#results', as: :results
  get '/simulador/resultados/imprimir', to: 'votes#print', as: :print
  post '/vote', to: 'votes#create', as: :vote
  get '/:position/:number', to: 'candidates#show', as: :candidates
  get '/estatisticas(/:state/:position)', to: 'stats#charts', as: :charts
  get '/politica-de-privacidade', to: 'elections#politics', as: :politics
  get '/reportar-erro', to: 'issues#new', as: :issue

  root 'elections#index'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>A Urna - Admin</title>
  <meta name="robots" content="noindex">
  <%= stylesheet_link_tag 'zone/application', media: 'all' %>
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/favicon.ico" type="image/x-icon">
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="wrapper">

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/zone">A Urna Admin</a>
      </div>
      <!-- /.navbar-header -->

      <div class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
          <ul class="nav" id="side-menu">
            <li><%= link_to zone_root_path do %><i class="fa fa-dashboard fa-fw"></i> Dashboard</a><% end %></li>
            <li><%= link_to zone_elections_path do %><i class="fa fa-check-square-o fa-fw"></i> Eleições</a><% end %></li>
            <li><%= link_to zone_candidates_path do %><i class="fa fa-users fa-fw"></i> Candidatos</a><% end %></li>
            <li><%= link_to zone_issues_path do %><i class="fa fa-envelope-o fa-fw"></i> Mensagens</a><% end %></li>
            <li><%= link_to zone_users_path do %><i class="fa fa-user fa-fw"></i> Usuários</a><% end %></li>

            <li>
              <a href="/zone/stats"><i class="fa fa-bar-chart-o fa-fw"></i> Estatísticas</a>
            </li>
          </ul>
        </div>
      </div><!-- /.navbar-static-side -->

    </nav>

    <div id="page-wrapper">
      <div class="row">
        <div class="col-lg-12">
          <%= render 'commons/flash'%>

          <%= yield %>

        </div>
      </div>
    </div>

  </div>

  <%= javascript_include_tag 'zone/application' %>

  <%= yield :javascript %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='pt'>
  <head>
    <%= render 'commons/head' %>
  </head>

  <body>
    <script type="text/javascript">
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '294932487369019',
          xfbml      : true,
          version    : 'v2.1'
        });
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>

    <div class="wrapper">
      <%= yield %>
      <div class="push"></div>
    </div>

    <div id="f" data-role="footer">
      <%= image_tag 'aurna-white-100.png', class: 'img-responsive logo' %>
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <%= link_to 'Políticas de Privacidade', politics_path %> |
            <%= link_to 'Reportar um erro', issue_path %>
            <%= link_to image_tag('wipcodes.png', alt: 'wip.codes', class: 'img-responsive pull-right'), 'http://wip.codes', title: 'Wip.Codes' %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= javascript_include_tag 'application' %>

  <%= yield :javascript %>

  <script type="text/javascript">
    var _gauges = _gauges || [];
    (function() {
      var t   = document.createElement('script');
      t.type  = 'text/javascript';
      t.async = true;
      t.id    = 'gauges-tracker';
      t.setAttribute('data-site-id', '542097ad8bfdf716e900343a');
      t.src = '//secure.gaug.es/track.js';
      var s = document.getElementsByTagName('script')[0];
      s.parentNode.insertBefore(t, s);
    })();
  </script>

  </body>
</html>

app/views/layouts/print.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>A Urna</title>
  <meta name="robots" content="noindex">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>